name: Build & Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Create Tag
        run: |
          TAG_NAME="v1.1.1-$(date +%Y%m%d)"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME
              
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/WebastoHeater-*.apk
          tag_name: ${{ env.TAG_NAME }}
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}