name: Build & Release APK

on:
  workflow_dispatch:
    inputs:
      version:
        description: 1.1.0
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Update firmware version in code
        run: |
          VERSION="${{ inputs.version }}"
          sed -i 's/versionName = ".*"/versionName = "'"$VERSION"'"/' app/build.gradle.kts
          echo "Updated versionName to $VERSION"

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Create tag
        run: |
          VERSION="${{ inputs.version }}"
          TAG_NAME="v$VERSION"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add app/build.gradle.kts
          git commit -m "Update firmware version to $VERSION" || echo "No changes to commit"
          git tag -f $TAG_NAME
          git push -f origin $TAG_NAME
              
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/WebastoHeater-*.apk
          tag_name: ${{ env.TAG_NAME }}
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
